<?php

namespace Database\Seeders;

use App\Models\CustomerProfile;
use App\Models\User;
use App\Models\UserAddress;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Sofía Hernández López',
                    'username' => 'cliente_001',
                    'email' => 'cliente001@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC001',
                    'status' => 'activo',
                    'commercial_name' => 'Sofía Hernández',
                    'credit_limit' => 8500.00,
                    'credit_days' => 7,
                    'discount_percent' => 3.00,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Centro',
                    'notes' => 'Persona física con actividad empresarial.',
                ],
                'address' => [
                    'alias' => 'Principal',
                    'contact_name' => 'Sofía Hernández López',
                    'street' => 'Av. Hidalgo',
                    'external_number' => '128',
                    'internal_number' => null,
                    'neighborhood' => 'Centro',
                    'zip_code' => '45400',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Frente al kiosco principal',
                    'phone' => '3310000001',
                    'email' => 'cliente001@ecommerce.com',
                    'rfc_curp' => 'HELS9203148K1',
                    'tipo_persona' => 'F',
                    'clave_regimen_fiscal' => '612',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Tecno Insumos del Bajío SA de CV',
                    'username' => 'cliente_002',
                    'email' => 'cliente002@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC002',
                    'status' => 'activo',
                    'commercial_name' => 'Tecno Insumos Bajío',
                    'credit_limit' => 45000.00,
                    'credit_days' => 15,
                    'discount_percent' => 2.50,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Norte',
                    'notes' => 'Persona moral, compra componentes por volumen.',
                ],
                'address' => [
                    'alias' => 'Matriz',
                    'contact_name' => 'Mariana López Torres',
                    'street' => 'Av. Patria',
                    'external_number' => '845',
                    'internal_number' => '12',
                    'neighborhood' => 'Jardines Universidad',
                    'zip_code' => '45420',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Torre corporativa, piso 3',
                    'phone' => '3310000002',
                    'email' => 'cliente002@ecommerce.com',
                    'rfc_curp' => 'TIB210518Q72',
                    'tipo_persona' => 'M',
                    'clave_regimen_fiscal' => '601',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Carlos Martín Ruiz Vega',
                    'username' => 'cliente_003',
                    'email' => 'cliente003@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC003',
                    'status' => 'activo',
                    'commercial_name' => 'Ruiz Reparaciones',
                    'credit_limit' => 12000.00,
                    'credit_days' => 30,
                    'discount_percent' => 5.00,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Sur',
                    'notes' => 'Persona física, taller de reparación de equipos.',
                ],
                'address' => [
                    'alias' => 'Taller',
                    'contact_name' => 'Carlos Martín Ruiz Vega',
                    'street' => 'Calle Morelos',
                    'external_number' => '230',
                    'internal_number' => null,
                    'neighborhood' => 'Jalisco',
                    'zip_code' => '45500',
                    'city' => 'Guadalajara',
                    'state' => 'Jalisco',
                    'references' => 'Local con cortina azul',
                    'phone' => '3310000003',
                    'email' => 'cliente003@ecommerce.com',
                    'rfc_curp' => 'RUVC880721LQ2',
                    'tipo_persona' => 'F',
                    'clave_regimen_fiscal' => '612',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Soluciones Cloud Noroeste SA de CV',
                    'username' => 'cliente_004',
                    'email' => 'cliente004@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC004',
                    'status' => 'activo',
                    'commercial_name' => 'Cloud Noroeste',
                    'credit_limit' => 65000.00,
                    'credit_days' => 21,
                    'discount_percent' => 4.50,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Oriente',
                    'notes' => 'Persona moral, compra equipo para centros de datos.',
                ],
                'address' => [
                    'alias' => 'Oficinas',
                    'contact_name' => 'Laura Sánchez Medina',
                    'street' => 'Av. Empresarios',
                    'external_number' => '88',
                    'internal_number' => null,
                    'neighborhood' => 'Puerta de Hierro',
                    'zip_code' => '45430',
                    'city' => 'Zapopan',
                    'state' => 'Jalisco',
                    'references' => 'Recepción del edificio norte',
                    'phone' => '3310000004',
                    'email' => 'cliente004@ecommerce.com',
                    'rfc_curp' => 'SCN190904R45',
                    'tipo_persona' => 'M',
                    'clave_regimen_fiscal' => '601',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Valeria Núñez García',
                    'username' => 'cliente_005',
                    'email' => 'cliente005@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC005',
                    'status' => 'suspendido_credito',
                    'commercial_name' => 'VG Accesorios Móviles',
                    'credit_limit' => 18000.00,
                    'credit_days' => 21,
                    'discount_percent' => 4.00,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Poniente',
                    'notes' => 'Persona física, pendiente de revisión de cobranza.',
                ],
                'address' => [
                    'alias' => 'Principal',
                    'contact_name' => 'Valeria Núñez García',
                    'street' => 'Av. Tonaltecas',
                    'external_number' => '560',
                    'internal_number' => null,
                    'neighborhood' => 'Centro',
                    'zip_code' => '45400',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Dentro de plaza comercial',
                    'phone' => '3310000005',
                    'email' => 'cliente005@ecommerce.com',
                    'rfc_curp' => 'NUGV9506124S8',
                    'tipo_persona' => 'F',
                    'clave_regimen_fiscal' => '612',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Innovación Digital Rivera SAS',
                    'username' => 'cliente_006',
                    'email' => 'cliente006@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC006',
                    'status' => 'activo',
                    'commercial_name' => 'ID Rivera',
                    'credit_limit' => 30000.00,
                    'credit_days' => 15,
                    'discount_percent' => 3.75,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Centro',
                    'notes' => 'Persona moral, integrador de soluciones digitales.',
                ],
                'address' => [
                    'alias' => 'Sucursal',
                    'contact_name' => 'Gabriela Torres Mejía',
                    'street' => 'Calle Matamoros',
                    'external_number' => '32',
                    'internal_number' => null,
                    'neighborhood' => 'Loma Dorada',
                    'zip_code' => '45402',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Segundo local del pasillo principal',
                    'phone' => '3310000006',
                    'email' => 'cliente006@ecommerce.com',
                    'rfc_curp' => 'IDR220811K19',
                    'tipo_persona' => 'M',
                    'clave_regimen_fiscal' => '601',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Miguel Ángel Herrera Campos',
                    'username' => 'cliente_007',
                    'email' => 'cliente007@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC007',
                    'status' => 'baja',
                    'credit_limit' => 0.00,
                    'commercial_name' => 'Herrera Soporte Técnico',
                    'credit_days' => 0,
                    'discount_percent' => 0.00,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Norte',
                    'notes' => 'Persona física, cliente inactivo temporalmente.',
                ],
                'address' => [
                    'alias' => 'Local',
                    'contact_name' => 'Miguel Ángel Herrera Campos',
                    'street' => 'Calle 5 de Mayo',
                    'external_number' => '77',
                    'internal_number' => null,
                    'neighborhood' => 'Zalatitán',
                    'zip_code' => '45410',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Entre la papelería y la estética',
                    'phone' => '3310000007',
                    'email' => 'cliente007@ecommerce.com',
                    'rfc_curp' => 'HECM870502PZ5',
                    'tipo_persona' => 'F',
                    'clave_regimen_fiscal' => '612',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Mayorista Electrónica Roma SA de CV',
                    'username' => 'cliente_008',
                    'email' => 'cliente008@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC008',
                    'status' => 'activo',
                    'commercial_name' => 'Electrónica Roma',
                    'credit_limit' => 78000.00,
                    'credit_days' => 14,
                    'discount_percent' => 3.50,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Sur',
                    'notes' => 'Persona moral con crecimiento constante.',
                ],
                'address' => [
                    'alias' => 'Principal',
                    'contact_name' => 'Andrea Vega Salas',
                    'street' => 'Av. Río Nilo',
                    'external_number' => '104',
                    'internal_number' => '3',
                    'neighborhood' => 'Lomas del Camichín',
                    'zip_code' => '45417',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Bodega 3, planta baja',
                    'phone' => '3310000008',
                    'email' => 'cliente008@ecommerce.com',
                    'rfc_curp' => 'MER180227T66',
                    'tipo_persona' => 'M',
                    'clave_regimen_fiscal' => '601',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Ana Martínez Salcedo',
                    'username' => 'cliente_009',
                    'email' => 'cliente009@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC009',
                    'status' => 'activo',
                    'commercial_name' => 'Ana Smart Home',
                    'credit_limit' => 22000.00,
                    'credit_days' => 30,
                    'discount_percent' => 6.00,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Poniente',
                    'notes' => 'Persona física, buen historial de pagos.',
                ],
                'address' => [
                    'alias' => 'Showroom',
                    'contact_name' => 'Ana Martínez Salcedo',
                    'street' => 'Calle Vallarta',
                    'external_number' => '901',
                    'internal_number' => null,
                    'neighborhood' => 'El Rosario',
                    'zip_code' => '44890',
                    'city' => 'Guadalajara',
                    'state' => 'Jalisco',
                    'references' => 'Entrada por estacionamiento lateral',
                    'phone' => '3310000009',
                    'email' => 'cliente009@ecommerce.com',
                    'rfc_curp' => 'MASA900128MN3',
                    'tipo_persona' => 'F',
                    'clave_regimen_fiscal' => '612',
                    'is_default' => true,
                ],
            ],
            [
                'user' => [
                    'role_id' => 6,
                    'name' => 'Distribuidora Hardware Central SA de CV',
                    'username' => 'cliente_010',
                    'email' => 'cliente010@ecommerce.com',
                    'password' => Hash::make('password123'),
                ],
                'profile' => [
                    'id_microsip' => 'MIC010',
                    'status' => 'activo',
                    'commercial_name' => 'Hardware Central',
                    'credit_limit' => 95000.00,
                    'credit_days' => 30,
                    'discount_percent' => 5.25,
                    'assigned_seller_id' => null,
                    'route' => 'Ruta Oriente',
                    'notes' => 'Persona moral, pide surtido semanal.',
                ],
                'address' => [
                    'alias' => 'Principal',
                    'contact_name' => 'Roberto Díaz Molina',
                    'street' => 'Calle Zaragoza',
                    'external_number' => '64',
                    'internal_number' => null,
                    'neighborhood' => 'Centro',
                    'zip_code' => '45400',
                    'city' => 'Tonalá',
                    'state' => 'Jalisco',
                    'references' => 'Esquina con Hidalgo, portón negro',
                    'phone' => '3310000010',
                    'email' => 'cliente010@ecommerce.com',
                    'rfc_curp' => 'DHC200603R91',
                    'tipo_persona' => 'M',
                    'clave_regimen_fiscal' => '601',
                    'is_default' => true,
                ],
            ],
        ];

        foreach ($customers as $customerData) {
            $userData = $customerData['user'];
            $profileData = $customerData['profile'];
            $addressData = $customerData['address'];

            $user = User::updateOrCreate(
                ['email' => $userData['email']],
                $userData
            );

            CustomerProfile::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'commercial_name' => $profileData['commercial_name'],
                    'id_microsip' => $profileData['id_microsip'],
                    'status' => $profileData['status'],
                    'credit_limit' => $profileData['credit_limit'],
                    'credit_days' => $profileData['credit_days'],
                    'discount_percent' => $profileData['discount_percent'],
                    'assigned_seller_id' => $profileData['assigned_seller_id'],
                    'route' => $profileData['route'],
                    'notes' => $profileData['notes'],
                ]
            );

            UserAddress::updateOrCreate(
                [
                    'user_id' => $user->id,
                    'alias' => $addressData['alias'],
                ],
                [
                    'contact_name' => $addressData['contact_name'],
                    'street' => $addressData['street'],
                    'external_number' => $addressData['external_number'],
                    'internal_number' => $addressData['internal_number'],
                    'neighborhood' => $addressData['neighborhood'],
                    'zip_code' => $addressData['zip_code'],
                    'city' => $addressData['city'],
                    'state' => $addressData['state'],
                    'references' => $addressData['references'],
                    'phone' => $addressData['phone'],
                    'email' => $addressData['email'],
                    'rfc_curp' => $addressData['rfc_curp'],
                    'tipo_persona' => $addressData['tipo_persona'],
                    'clave_regimen_fiscal' => $addressData['clave_regimen_fiscal'],
                    'is_default' => $addressData['is_default'],
                ]
            );
        }
    }
}
